version: "3"
services:
  crabcdb:
    image: mysql:latest
    networks:
      - crabc_network
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    volumes:
      - /opt/data/crabc/mysql:/var/lib/mysql
      # 加载库表数据
      - /opt/data/crabc/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD:=admin123
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
  crabc-admin:
    image: crabc/crabc-admin:latest
    container_name: crabc-admin
    depends_on:
      - crabcdbexit
    networks:
      - crabc_network
    ports:
      - "9377:9377"
    environment:
      - db_url=jdbc:mysql://crabcdb:3306/crabc
      - db_user=admindb
      - db_pwd=admin123

networks:
  crabc_network: