services:
  backend:
    container_name: azimutt-backend
    image: ghcr.io/azimuttapp/azimutt:main
    restart: always
    ports: # Docker need to expose ports for you to access your app.
      - 4000:4000
    env_file: .env
    environment:
      DATABASE_URL: "ecto://postgres:postgres@supabase_db_dev-stacks.orb.local:5432/nocodb?currentSchema=db_docs" # Template : "ecto://db_user:db_password@ip_or_compose_service_name/db_name"
      SECRET_KEY_BASE: "4a563e3f21310c0f418a831f4af45cbf4cc7803d1f46acd99b4e24559cfdabe1f5a64dd129b28a586dda79812b5e3a2b0bd82e5c06e8fdd5365064aca897d2db" # Can literally be anything, but generally generated randomly by tools like mix phx.gen.secret
volumes:
  pg-data:
