@startuml
title 建木自动化集成平台 - 主服务 - Components

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_WITH_LEGEND()

Container(3, "SPA单页面应用", "TypeScript and Vue 3.0", "Provides all of the Jianmu functionality to customers via their web browser.")

Container_Boundary("4_boundary", "主服务") {
  Component(10, "参数管理", "参数上下文")
  Component(5, "DSL解析器", "DSL语法解析器")
  Component(6, "触发器", "触发器上下文")
  Component(7, "流程流转", "流程上下文")
  Component(8, "el引擎", "表达式引擎")
  Component(9, "任务分发", "任务上下文")
}

Rel_D(3, 6, "启动流程或任务", "Rest API")
Rel_D(3, 5, "提交DSL定义", "Rest API")
Rel_D(5, 7, "保存流程定义", "Java API")
Rel_D(6, 7, "触发流程启动", "Java API")
Rel_D(6, 9, "直接触发任务启动", "Java API")
Rel_D(7, 9, "任务节点激活事件触发任务启动", "Java API")
Rel_D(7, 9, "任务节点中止事件触发任务中止", "Java API")
Rel_D(7, 8, "执行表达式", "Java API")
Rel_D(8, 7, "返回表达式结果", "Java API")
Rel_D(9, 7, "返回任务执行状态", "Java API")
Rel_D(7, 10, "读取参数信息", "Java API")
Rel_D(7, 10, "流程执行结果参数写入", "Java API")
Rel_D(9, 10, "读取参数信息", "Java API")
Rel_D(9, 10, "任务执行结果参数写入", "Java API")
@enduml