@startuml
title 建木自动化集成平台 - docker-worker - Components

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_WITH_LEGEND()

Container(4, "主服务", "主服务")

Container_Boundary("12_boundary", "docker-worker") {
  Component(13, "daemon", "worker守护容器")
  Component(14, "代码编译", "任务运行容器")
  Component(15, "Ansible执行", "任务运行容器")
}

Rel_D(13, 4, "获取任务执行", "http/https")
Rel_D(13, 4, "返回执行结果", "http/https")
Rel_D(13, 14, "启动容器", "Docker API")
Rel_D(13, 15, "启动容器", "Docker API")
@enduml